### ISSUE TITLE
Errors installing dependencies for development

### ISSUE THREAD

**Issue by EdenSG** [cutestrap/cutestrap#1]
When installing the node_modules for this project, there were several errors thrown during the `npm install`:

````
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global node-gyp@3.3.1 should be installed with -g
````

Then, when `bower install` in run, this is thrown:
````
(node:8568) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
````

Finally, `gulp` fails as well:
````
(node:8632) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:442
    throw err;
    ^

Error: Cannot find module 'gulp-include'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/edensg/Desktop/Desktop/GCVI/McCrae Day/styleguide/cutestrap/gulpfile.js:10:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
````

---

I'm not sure how much of this you have control over and how much is just a result of dependencies and their messiness. Would it worth trying other (older) node versions perhaps, or are there other things that should be installed (locally or globally)?

**Comment by tylerchilds** [comment]
I think the four things I have installed globally are node, npm, bower, and kss-node (`npm install -g kss`). What OS are you on and what output do you get when you run `$ node -v && npm -v && bower -v && kss-node --version`?


I'm on OSX 10.11.4 and these are my results.
```
v5.11.0
3.8.6
1.4.1
2.1.0
```

**Comment by EdenSG** [comment]
I'm on OS X 10.11.5. Here are my results:
````
v6.2.0
3.8.9
1.7.9
The "kss-node" tool name is deprecated; use "kss" instead.
````
However, `kss --version` reveals I've got version `3.0.0-beta.12`. I'll try uninstalling it and installing 2.1.0.

**Comment by EdenSG** [comment]
I managed to get it working, but I needed to install version 2 of `kss`, and I also needed to install `gulp-include`. These are things that could be included in the `package.json`.

**Comment by EdenSG** [comment]
#2 should fix this.

**Comment by tylerchilds** [comment]
@EdenSG Thanks! Merged in your PR!

**Comment by EdenSG** [comment]
👍
